spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NEMS
    username: postgres
    password: bgne

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE